project_prompt = """
- Before beginning work on this feature, write a short haiku.
- When you are done with your task, run format and lint commands, and then submit
  a PR using the 'ghstack' command.
- We ONLY write end to end tests, do NOT use mocks.
- When you make a new tool, the prompt goes in system_prompt in
  codecmp/tools/init_project.py
"""

[commands]
format = ["./run_format.sh"]
lint = ["./run_lint.sh"]
ghstack = ["uv", "tool", "run", "ghstack"]
[commands.test]
command = ["./run_test.sh"]
doc = "Accepts a pytest-style test selector as an argument to run a specific test."
